AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dcc-phi-checker lambda

Metadata:
  AWS::ServerlessRepo::Application:
    Name: "dcc-phi-checker"
    Description: "A lambda function for adding phi spotchecking."
    Author: "Sage-Bionetworks"
    SpdxLicenseId: "Apache-2.0"
    # paths are relative to .aws-sam/build directory
    LicenseUrl: "LICENSE"
    ReadmeUrl: "README.md"
    Labels: ["serverless", "template", "github", "quick-start"]
    HomePageUrl: "https://github.com/Sage-Bionetworks-IT/lambda-template"
    SemanticVersion: "0.0.1"
    SourceCodeUrl: "https://github.com/Sage-Bionetworks-IT/lambda-template/tree/0.0.3"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30

Resources:
  DetectPHIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dcc_phi_reporter/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt DetectPHIFunctionRole.Arn

  DetectPHIFunctionRole: # execute lambda function with this role
    Type: AWS::IAM::Role
    Properties:
      Description: S3Batch trust, s3 access, & lambda execution
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
                - batchoperations.s3.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CustomS3Batch
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action: "s3:*"
                Resource: "*"

Outputs:
  DetectPHIFunctionArn:
    Description: "DetectPHI Lambda Function ARN"
    Value: !GetAtt DetectPHIFunction.Arn
  DetectPHIFunctionRoleArn:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DetectPHIFunctionRole.Arn
